name: publish
on: [ push ] # todo: change to "tag" or something
jobs:
    artifacts:
        runs-on: ${{ matrix.os-name }}-latest
        strategy:
            matrix:
                os-name:
                    - windows
                    - ubuntu
                    - macos
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 7.x.x
            - name: install vulkan
              uses: humbletim/setup-vulkan-sdk@v1.2.0
              with:
                vulkan-query-version: latest
                vulkan-use-cache: true
                vulkan-components: Vulkan-Headers, Vulkan-Loader
            - name: pull optick
              shell: bash
              run: git clone --branch fix-vulkan --recursive https://github.com/qbojj/optick.git  
            - name: build optick!
              shell: bash
              run: |
                dotnet build -c Release
                dotnet Optick.NET.RedistBuilder/bin/Release/net7.0/Optick.NET.RedistBuilder.dll build-artifact
            - name: push artifact
              uses: actions/upload-artifact@v3
              with:
                name: artifact-${{ matrix.os-name }}
                path: artifacts/artifact-*.zip